#!/usr/bin/env bash

cd `dirname $0`

./rebar get-deps

./rebar compile

erl -boot start_sasl -pa $PWD/ebin -pa $PWD/deps/*/ebin -pa $ERL_LIBS/sync/ebin -config mongoltweet.config  -s crypto -s inets -s ssl -s lhttpc -s mochiweb -s webmachine -s mongoltweet start -mnesia dir '"."'
