#!/usr/bin/env bash
./rebar get-deps

./rebar compile

erl -boot start_sasl -pa ebin -pa deps/hackney/ebin -pa deps/hackney_lib/ebin -pa deps/mimetypes/deps -config mongoltweet.config -s mongoltweet start
